### ISSUE TITLE
Downloading Icons fails

### ISSUE THREAD

**Issue by cl0rm** [JeeZeh/steam-shortcut-generator#1]
for me (windows 10 2004 x64)
Downloading the icons fails for every single one (this includes common games like CSGO).
Interestingly, When using the Steam way of right clicking, this also only adds shortcuts to 3-4 games out of 100.
However everything else works.

Thanks for sharing the script.

**Comment by jesse-ashmore** [comment]
Thanks, will investigate now and get back to you soon!

**Comment by jesse-ashmore** [comment]
I'm seeing the same thing, working on it now

**Comment by jesse-ashmore** [comment]
Okay, so SteamDB have started issuing IP bans to users submitting requests without a valid User Agent string. I could fix it by adding one, but I want to figure out how to pull the icons directly from Steam. Will update hopefully soon with a fix

**Comment by jesse-ashmore** [comment]
Working on a fix at the moment to not use SteamDB, will require providing your SteamID and possibly pip installing pillow. Will continue working tomorrow

**Comment by jesse-ashmore** [comment]
@cl0rm I've just published a fix. 

This tool used to use SteamDB to fetch the hi-res .ico file for each game, but scraping was causing some IP-ban issues (sorry). It has been rewritten to use the SteamAPI (in combination with your username) to fetch the icons from the Steam CDN directly. Unfortunately, the quality for each icon is a low-res jpg, as the API does not provide the .ico links - I will investigate this and fix it soon hopefully. If successful, I'll be able to remove the Pillow dependency too!

Remember to run `[your python3 alias] -m pip install pillow` before trying it. Let me know if there are any issues

**Comment by jesse-ashmore** [comment]
I think this is fixed, but I still haven't found a way to get high quality icons from SteamCDN.
