### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by JoshuaVandaele** [JeeZeh/steam-shortcut-generator#6]
Using the provided requirements.txt file, Pillow doesn't work with this error:
```
setup.py:45: RuntimeWarning: Pillow 9.0.1 does not support Python 3.11 and does not provide prebuilt Windows binaries. We do not recommend building from source on Windows.
        lambda: warnings.warn(
      [end of output]

error: legacy-install-failure
```

**Comment by JoshuaVandaele** [comment]
I'd like to add it does not work with Python 3.6 unlike what the Readme states for the exact same reason. Checking Pypi (https://pypi.org/project/Pillow/9.0.1/#files) we can see that Python 3.7.0 is the minimal version and Python 3.10 is the maximal one.

**Comment by ayesc9000** [comment]
Also unable to use this with Python 3.11. An update to the README to reflect this would be appreciated.

**Comment by jesse-ashmore** [comment]
Hi all,

Sorry for the delay. Thanks for reporting the issue, this should be resolvable with some tweaking of the `requirements.txt` file.
